//
//  UIImage+Shapes.swift
//  BiometricX
//
//  Created by Prashant Shrestha on 5/26/20.
//  Copyright © 2020 Inficare. All rights reserved.
//

import UIKit

extension UIImage {
    
    static func touchIdImage() -> UIImage {
        return UIGraphicsImageRenderer(size: CGSize(width: 1024, height: 1024)).image { _ in
            // This code was generated by Trial version of PaintCode, therefore cannot be used for commercial purposes.
            // http://www.paintcodeapp.com

            //// General Declarations
            let context = UIGraphicsGetCurrentContext()!

            //// Color Declarations
            let strokeColor = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1.000)

            //// Group_2
            //// Rectangle_2 Drawing


            //// iconfinder_Touch_ID_363335
            context.saveGState()
            context.beginTransparencyLayer(auxiliaryInfo: nil)

            //// Clip iconfinder_Touch_ID_
            let iconfinder_Touch_ID_Path = UIBezierPath(rect: CGRect(x: 7.02, y: 0, width: 1010.45, height: 1024))
            iconfinder_Touch_ID_Path.addClip()


            //// Group_271
            //// Group_270
            //// Path_153 Drawing
            let path_153Path = UIBezierPath()
            path_153Path.move(to: CGPoint(x: 70.46, y: 282.98))
            path_153Path.addLine(to: CGPoint(x: 70.21, y: 283.47))
            path_153Path.addCurve(to: CGPoint(x: 26.34, y: 616.73), controlPoint1: CGPoint(x: 17.84, y: 386.25), controlPoint2: CGPoint(x: 2.36, y: 503.9))
            strokeColor.setStroke()
            path_153Path.lineWidth = 16
            path_153Path.lineCapStyle = .round
            path_153Path.stroke()


            //// Path_154 Drawing
            let path_154Path = UIBezierPath()
            path_154Path.move(to: CGPoint(x: 738.39, y: 59.8))
            path_154Path.addCurve(to: CGPoint(x: 112.04, y: 215.2), controlPoint1: CGPoint(x: 519.61, y: -47.71), controlPoint2: CGPoint(x: 255.2, y: 17.89))
            strokeColor.setStroke()
            path_154Path.lineWidth = 16
            path_154Path.lineCapStyle = .round
            path_154Path.stroke()


            //// Path_155 Drawing
            let path_155Path = UIBezierPath()
            path_155Path.move(to: CGPoint(x: 1009.62, y: 412.8))
            path_155Path.addLine(to: CGPoint(x: 1010.05, y: 414.96))
            path_155Path.addCurve(to: CGPoint(x: 805.06, y: 99.31), controlPoint1: CGPoint(x: 985.2, y: 287.16), controlPoint2: CGPoint(x: 911.71, y: 173.99))
            strokeColor.setStroke()
            path_155Path.lineWidth = 16
            path_155Path.lineCapStyle = .round
            path_155Path.stroke()






            //// Path_158 Drawing
            let path_158Path = UIBezierPath()
            path_158Path.move(to: CGPoint(x: 387.88, y: 999.34))
            path_158Path.addLine(to: CGPoint(x: 389.54, y: 997.44))
            path_158Path.addCurve(to: CGPoint(x: 516.45, y: 506.73), controlPoint1: CGPoint(x: 506.53, y: 862.86), controlPoint2: CGPoint(x: 553.52, y: 681.15))
            strokeColor.setStroke()
            path_158Path.lineWidth = 16
            path_158Path.lineCapStyle = .round
            path_158Path.stroke()


            //// Path_159 Drawing
            let path_159Path = UIBezierPath()
            path_159Path.move(to: CGPoint(x: 431.86, y: 807.43))
            path_159Path.addLine(to: CGPoint(x: 432.65, y: 805.41))
            path_159Path.addCurve(to: CGPoint(x: 323.96, y: 976.01), controlPoint1: CGPoint(x: 408.24, y: 868.99), controlPoint2: CGPoint(x: 371.28, y: 927.01))
            strokeColor.setStroke()
            path_159Path.lineWidth = 16
            path_159Path.lineCapStyle = .round
            path_159Path.stroke()


            //// Path_160 Drawing
            let path_160Path = UIBezierPath()
            path_160Path.move(to: CGPoint(x: 458.17, y: 1012.92))
            path_160Path.addLine(to: CGPoint(x: 457.94, y: 1013.21))
            path_160Path.addCurve(to: CGPoint(x: 580.06, y: 504.53), controlPoint1: CGPoint(x: 570.36, y: 869.32), controlPoint2: CGPoint(x: 614.9, y: 683.77))
            path_160Path.addLine(to: CGPoint(x: 579.34, y: 499.86))
            path_160Path.addLine(to: CGPoint(x: 579.37, y: 500))
            path_160Path.addCurve(to: CGPoint(x: 505.39, y: 450.1), controlPoint1: CGPoint(x: 572.72, y: 465.79), controlPoint2: CGPoint(x: 539.6, y: 443.45))
            path_160Path.addCurve(to: CGPoint(x: 455.49, y: 524.08), controlPoint1: CGPoint(x: 471.18, y: 456.75), controlPoint2: CGPoint(x: 448.84, y: 489.87))
            path_160Path.addCurve(to: CGPoint(x: 455.71, y: 525.16), controlPoint1: CGPoint(x: 455.56, y: 524.44), controlPoint2: CGPoint(x: 455.63, y: 524.8))
            path_160Path.addLine(to: CGPoint(x: 456.1, y: 524.82))
            path_160Path.addLine(to: CGPoint(x: 456.84, y: 528.55))
            path_160Path.addCurve(to: CGPoint(x: 455.08, y: 729.72), controlPoint1: CGPoint(x: 469.76, y: 595.04), controlPoint2: CGPoint(x: 469.17, y: 663.46))
            strokeColor.setStroke()
            path_160Path.lineWidth = 16
            path_160Path.lineCapStyle = .round
            path_160Path.stroke()


            //// Path_161 Drawing
            let path_161Path = UIBezierPath()
            path_161Path.move(to: CGPoint(x: 399.35, y: 565.66))
            path_161Path.addLine(to: CGPoint(x: 399, y: 563.12))
            path_161Path.addCurve(to: CGPoint(x: 268.27, y: 942.78), controlPoint1: CGPoint(x: 418.7, y: 703.3), controlPoint2: CGPoint(x: 370.1, y: 844.45))
            strokeColor.setStroke()
            path_161Path.lineWidth = 16
            path_161Path.lineCapStyle = .round
            path_161Path.stroke()


            //// Path_162 Drawing
            let path_162Path = UIBezierPath()
            path_162Path.move(to: CGPoint(x: 654.42, y: 623.25))
            path_162Path.addLine(to: CGPoint(x: 654.42, y: 625.47))
            path_162Path.addCurve(to: CGPoint(x: 641.58, y: 492.11), controlPoint1: CGPoint(x: 654.42, y: 580.71), controlPoint2: CGPoint(x: 650.12, y: 536.05))
            path_162Path.addLine(to: CGPoint(x: 640.81, y: 487.43))
            path_162Path.addLine(to: CGPoint(x: 640.89, y: 487.82))
            path_162Path.addCurve(to: CGPoint(x: 493.5, y: 388.41), controlPoint1: CGPoint(x: 627.64, y: 419.67), controlPoint2: CGPoint(x: 561.65, y: 375.16))
            path_162Path.addCurve(to: CGPoint(x: 394.52, y: 485.67), controlPoint1: CGPoint(x: 443.98, y: 398.03), controlPoint2: CGPoint(x: 405.01, y: 436.33))
            strokeColor.setStroke()
            path_162Path.lineWidth = 16
            path_162Path.lineCapStyle = .round
            path_162Path.stroke()


            //// Path_163 Drawing
            let path_163Path = UIBezierPath()
            path_163Path.move(to: CGPoint(x: 533.52, y: 1016.13))
            path_163Path.addLine(to: CGPoint(x: 535.64, y: 1013.02))
            path_163Path.addCurve(to: CGPoint(x: 650.69, y: 696.92), controlPoint1: CGPoint(x: 599.28, y: 918.66), controlPoint2: CGPoint(x: 638.79, y: 810.11))
            strokeColor.setStroke()
            path_163Path.lineWidth = 16
            path_163Path.lineCapStyle = .round
            path_163Path.stroke()


            //// Path_164 Drawing
            let path_164Path = UIBezierPath()
            path_164Path.move(to: CGPoint(x: 532.23, y: 323.7))
            path_164Path.addLine(to: CGPoint(x: 530.86, y: 323.6))
            path_164Path.addCurve(to: CGPoint(x: 329.34, y: 498.77), controlPoint1: CGPoint(x: 426.84, y: 316.32), controlPoint2: CGPoint(x: 336.61, y: 394.75))
            path_164Path.addCurve(to: CGPoint(x: 333.01, y: 551.2), controlPoint1: CGPoint(x: 328.11, y: 516.33), controlPoint2: CGPoint(x: 329.35, y: 533.98))
            path_164Path.addLine(to: CGPoint(x: 333.07, y: 549.74))
            path_164Path.addLine(to: CGPoint(x: 333.58, y: 552.33))
            path_164Path.addCurve(to: CGPoint(x: 210.16, y: 910.77), controlPoint1: CGPoint(x: 359.42, y: 685.28), controlPoint2: CGPoint(x: 312.38, y: 821.91))
            strokeColor.setStroke()
            path_164Path.lineWidth = 16
            path_164Path.lineCapStyle = .round
            path_164Path.stroke()


            //// Path_165 Drawing
            let path_165Path = UIBezierPath()
            path_165Path.move(to: CGPoint(x: 613.57, y: 1007))
            path_165Path.addLine(to: CGPoint(x: 615.93, y: 1002.94))
            path_165Path.addCurve(to: CGPoint(x: 700.69, y: 467.79), controlPoint1: CGPoint(x: 709.34, y: 841.16), controlPoint2: CGPoint(x: 739.53, y: 650.52))
            path_165Path.addLine(to: CGPoint(x: 702.28, y: 474.98))
            path_165Path.addLine(to: CGPoint(x: 702.45, y: 475.85))
            path_165Path.addCurve(to: CGPoint(x: 608.64, y: 346.74), controlPoint1: CGPoint(x: 691.8, y: 421.07), controlPoint2: CGPoint(x: 657.46, y: 373.8))
            strokeColor.setStroke()
            path_165Path.lineWidth = 16
            path_165Path.lineCapStyle = .round
            path_165Path.stroke()


            //// Path_166 Drawing
            let path_166Path = UIBezierPath()
            path_166Path.move(to: CGPoint(x: 256.57, y: 738.34))
            path_166Path.addLine(to: CGPoint(x: 256.86, y: 737.57))
            path_166Path.addCurve(to: CGPoint(x: 164.68, y: 866.82), controlPoint1: CGPoint(x: 237.59, y: 787.77), controlPoint2: CGPoint(x: 205.87, y: 832.25))
            strokeColor.setStroke()
            path_166Path.lineWidth = 16
            path_166Path.lineCapStyle = .round
            path_166Path.stroke()


            //// Path_167 Drawing
            let path_167Path = UIBezierPath()
            path_167Path.move(to: CGPoint(x: 769.19, y: 757.43))
            path_167Path.addLine(to: CGPoint(x: 769.86, y: 753.29))
            path_167Path.addCurve(to: CGPoint(x: 762.03, y: 454.49), controlPoint1: CGPoint(x: 785.57, y: 654.05), controlPoint2: CGPoint(x: 782.92, y: 552.77))
            path_167Path.addLine(to: CGPoint(x: 763.71, y: 462.58))
            path_167Path.addCurve(to: CGPoint(x: 467.61, y: 266.18), controlPoint1: CGPoint(x: 736.18, y: 326.58), controlPoint2: CGPoint(x: 603.62, y: 238.65))
            path_167Path.addCurve(to: CGPoint(x: 271.21, y: 562.28), controlPoint1: CGPoint(x: 331.61, y: 293.71), controlPoint2: CGPoint(x: 243.68, y: 426.28))
            path_167Path.addLine(to: CGPoint(x: 271.51, y: 562.22))
            path_167Path.addLine(to: CGPoint(x: 271.95, y: 564.45))
            path_167Path.addCurve(to: CGPoint(x: 276.03, y: 657.85), controlPoint1: CGPoint(x: 277.93, y: 595.21), controlPoint2: CGPoint(x: 279.3, y: 626.69))
            strokeColor.setStroke()
            path_167Path.lineWidth = 16
            path_167Path.lineCapStyle = .round
            path_167Path.stroke()


            //// Path_168 Drawing
            let path_168Path = UIBezierPath()
            path_168Path.move(to: CGPoint(x: 697.61, y: 982.82))
            path_168Path.addLine(to: CGPoint(x: 696.95, y: 984.18))
            path_168Path.addCurve(to: CGPoint(x: 752.11, y: 836.64), controlPoint1: CGPoint(x: 720.02, y: 936.88), controlPoint2: CGPoint(x: 738.49, y: 887.48))
            strokeColor.setStroke()
            path_168Path.lineWidth = 16
            path_168Path.lineCapStyle = .round
            path_168Path.stroke()


            //// Path_169 Drawing
            let path_169Path = UIBezierPath()
            path_169Path.move(to: CGPoint(x: 771.37, y: 326.94))
            path_169Path.addLine(to: CGPoint(x: 771.19, y: 326.68))
            path_169Path.addCurve(to: CGPoint(x: 825.5, y: 451.6), controlPoint1: CGPoint(x: 798.2, y: 363.86), controlPoint2: CGPoint(x: 816.74, y: 406.49))
            path_169Path.addLine(to: CGPoint(x: 825.21, y: 450.11))
            path_169Path.addLine(to: CGPoint(x: 826.56, y: 456.89))
            path_169Path.addCurve(to: CGPoint(x: 784.21, y: 940.88), controlPoint1: CGPoint(x: 858.07, y: 619), controlPoint2: CGPoint(x: 843.39, y: 786.71))
            strokeColor.setStroke()
            path_169Path.lineWidth = 16
            path_169Path.lineCapStyle = .round
            path_169Path.stroke()


            //// Path_170 Drawing
            let path_170Path = UIBezierPath()
            path_170Path.move(to: CGPoint(x: 386.44, y: 225.97))
            path_170Path.addLine(to: CGPoint(x: 384.91, y: 226.68))
            path_170Path.addCurve(to: CGPoint(x: 714.66, y: 267.17), controlPoint1: CGPoint(x: 493.53, y: 176.03), controlPoint2: CGPoint(x: 621.52, y: 191.75))
            strokeColor.setStroke()
            path_170Path.lineWidth = 16
            path_170Path.lineCapStyle = .round
            path_170Path.stroke()


            //// Path_171 Drawing
            let path_171Path = UIBezierPath()
            path_171Path.move(to: CGPoint(x: 120.82, y: 821.43))
            path_171Path.addLine(to: CGPoint(x: 121.25, y: 821.09))
            path_171Path.addCurve(to: CGPoint(x: 209.44, y: 572.04), controlPoint1: CGPoint(x: 195.13, y: 761.25), controlPoint2: CGPoint(x: 229.21, y: 665.03))
            path_171Path.addLine(to: CGPoint(x: 209.74, y: 574.68))
            path_171Path.addLine(to: CGPoint(x: 209.32, y: 572.56))
            path_171Path.addCurve(to: CGPoint(x: 320.55, y: 266.96), controlPoint1: CGPoint(x: 187.05, y: 457.96), controlPoint2: CGPoint(x: 229.83, y: 340.43))
            strokeColor.setStroke()
            path_171Path.lineWidth = 16
            path_171Path.lineCapStyle = .round
            path_171Path.stroke()


            //// Path_172 Drawing
            let path_172Path = UIBezierPath()
            path_172Path.move(to: CGPoint(x: 141.12, y: 527.37))
            path_172Path.addLine(to: CGPoint(x: 141.03, y: 525.06))
            path_172Path.addCurve(to: CGPoint(x: 147.82, y: 584.68), controlPoint1: CGPoint(x: 141.73, y: 545.08), controlPoint2: CGPoint(x: 144, y: 565.01))
            path_172Path.addLine(to: CGPoint(x: 148.5, y: 587.09))
            path_172Path.addLine(to: CGPoint(x: 148.76, y: 588.39))
            path_172Path.addCurve(to: CGPoint(x: 84.46, y: 769.96), controlPoint1: CGPoint(x: 161.92, y: 656.1), controlPoint2: CGPoint(x: 137.3, y: 725.62))
            strokeColor.setStroke()
            path_172Path.lineWidth = 16
            path_172Path.lineCapStyle = .round
            path_172Path.stroke()


            //// Path_173 Drawing
            let path_173Path = UIBezierPath()
            path_173Path.move(to: CGPoint(x: 895.28, y: 486.62))
            path_173Path.addCurve(to: CGPoint(x: 886.75, y: 437.69), controlPoint1: CGPoint(x: 892.87, y: 470.33), controlPoint2: CGPoint(x: 890.02, y: 454.02))
            path_173Path.addLine(to: CGPoint(x: 886.68, y: 437.69))
            path_173Path.addLine(to: CGPoint(x: 886.93, y: 438.98))
            path_173Path.addCurve(to: CGPoint(x: 445.6, y: 141.3), controlPoint1: CGPoint(x: 847.26, y: 234.91), controlPoint2: CGPoint(x: 649.67, y: 101.63))
            path_173Path.addCurve(to: CGPoint(x: 146.72, y: 445.44), controlPoint1: CGPoint(x: 292.62, y: 171.03), controlPoint2: CGPoint(x: 173.78, y: 291.96))
            strokeColor.setStroke()
            path_173Path.lineWidth = 16
            path_173Path.lineCapStyle = .round
            path_173Path.stroke()


            //// Path_174 Drawing
            let path_174Path = UIBezierPath()
            path_174Path.move(to: CGPoint(x: 873.86, y: 867.39))
            path_174Path.addLine(to: CGPoint(x: 873.36, y: 869.26))
            path_174Path.addCurve(to: CGPoint(x: 904.19, y: 575.94), controlPoint1: CGPoint(x: 898.97, y: 773.71), controlPoint2: CGPoint(x: 909.37, y: 674.73))
            strokeColor.setStroke()
            path_174Path.lineWidth = 16
            path_174Path.lineCapStyle = .round
            path_174Path.stroke()


            //// Path_175 Drawing
            let path_175Path = UIBezierPath()
            path_175Path.move(to: CGPoint(x: 576.36, y: 75.25))
            path_175Path.addLine(to: CGPoint(x: 579.18, y: 75.63))
            path_175Path.addCurve(to: CGPoint(x: 82.18, y: 450.14), controlPoint1: CGPoint(x: 338.52, y: 41.81), controlPoint2: CGPoint(x: 116, y: 209.48))
            path_175Path.addCurve(to: CGPoint(x: 85.98, y: 595.35), controlPoint1: CGPoint(x: 75.4, y: 498.42), controlPoint2: CGPoint(x: 76.68, y: 547.49))
            path_175Path.addLine(to: CGPoint(x: 86.97, y: 599.57))
            path_175Path.addLine(to: CGPoint(x: 87.14, y: 600.44))
            path_175Path.addCurve(to: CGPoint(x: 55.47, y: 710.9), controlPoint1: CGPoint(x: 94.87, y: 640.21), controlPoint2: CGPoint(x: 83.1, y: 681.27))
            strokeColor.setStroke()
            path_175Path.lineWidth = 16
            path_175Path.lineCapStyle = .round
            path_175Path.stroke()


            //// Path_176 Drawing
            let path_176Path = UIBezierPath()
            path_176Path.move(to: CGPoint(x: 960.61, y: 749.28))
            path_176Path.addLine(to: CGPoint(x: 960.72, y: 748.44))
            path_176Path.addCurve(to: CGPoint(x: 949.68, y: 432.34), controlPoint1: CGPoint(x: 973.65, y: 643.15), controlPoint2: CGPoint(x: 969.92, y: 536.47))
            path_176Path.addLine(to: CGPoint(x: 948.14, y: 425.23))
            path_176Path.addLine(to: CGPoint(x: 948.56, y: 427.34))
            path_176Path.addCurve(to: CGPoint(x: 652.42, y: 92.61), controlPoint1: CGPoint(x: 918.02, y: 270.23), controlPoint2: CGPoint(x: 804.63, y: 142.07))
            strokeColor.setStroke()
            path_176Path.lineWidth = 16
            path_176Path.lineCapStyle = .round
            path_176Path.stroke()


            context.endTransparencyLayer()
            context.restoreGState()

        }
    }
    
    
    static func faceIdImage() -> UIImage {
        return UIGraphicsImageRenderer(size: CGSize(width: 1024, height: 1024)).image { _ in
            // This code was generated by Trial version of PaintCode, therefore cannot be used for commercial purposes.
            // http://www.paintcodeapp.com

            //// Color Declarations
            let fillColor = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1.000)

            //// Face_ID-2 Drawing
            let face_ID2Path = UIBezierPath()
            face_ID2Path.move(to: CGPoint(x: 858, y: 1024))
            face_ID2Path.addLine(to: CGPoint(x: 743, y: 1024))
            face_ID2Path.addLine(to: CGPoint(x: 743, y: 1024))
            face_ID2Path.addCurve(to: CGPoint(x: 717, y: 998), controlPoint1: CGPoint(x: 728.64, y: 1024), controlPoint2: CGPoint(x: 717, y: 1012.36))
            face_ID2Path.addCurve(to: CGPoint(x: 743, y: 972), controlPoint1: CGPoint(x: 717, y: 983.64), controlPoint2: CGPoint(x: 728.64, y: 972))
            face_ID2Path.addLine(to: CGPoint(x: 858, y: 972))
            face_ID2Path.addLine(to: CGPoint(x: 857.87, y: 972))
            face_ID2Path.addCurve(to: CGPoint(x: 972, y: 857.87), controlPoint1: CGPoint(x: 920.9, y: 972), controlPoint2: CGPoint(x: 972, y: 920.9))
            face_ID2Path.addLine(to: CGPoint(x: 972, y: 743))
            face_ID2Path.addLine(to: CGPoint(x: 972, y: 743))
            face_ID2Path.addCurve(to: CGPoint(x: 998, y: 717), controlPoint1: CGPoint(x: 972, y: 728.64), controlPoint2: CGPoint(x: 983.64, y: 717))
            face_ID2Path.addCurve(to: CGPoint(x: 1024, y: 743), controlPoint1: CGPoint(x: 1012.36, y: 717), controlPoint2: CGPoint(x: 1024, y: 728.64))
            face_ID2Path.addLine(to: CGPoint(x: 1024, y: 858))
            face_ID2Path.addCurve(to: CGPoint(x: 858, y: 1024), controlPoint1: CGPoint(x: 1024, y: 949.53), controlPoint2: CGPoint(x: 949.53, y: 1024))
            face_ID2Path.close()
            face_ID2Path.move(to: CGPoint(x: 281, y: 1024))
            face_ID2Path.addLine(to: CGPoint(x: 166, y: 1024))
            face_ID2Path.addCurve(to: CGPoint(x: 0, y: 858), controlPoint1: CGPoint(x: 74.47, y: 1024), controlPoint2: CGPoint(x: 0, y: 949.53))
            face_ID2Path.addLine(to: CGPoint(x: 0, y: 743))
            face_ID2Path.addLine(to: CGPoint(x: -0, y: 743.02))
            face_ID2Path.addCurve(to: CGPoint(x: 26.01, y: 717.01), controlPoint1: CGPoint(x: -0, y: 728.65), controlPoint2: CGPoint(x: 11.64, y: 717.01))
            face_ID2Path.addCurve(to: CGPoint(x: 49.95, y: 732.86), controlPoint1: CGPoint(x: 36.44, y: 717.01), controlPoint2: CGPoint(x: 45.87, y: 723.25))
            face_ID2Path.addLine(to: CGPoint(x: 49.95, y: 732.85))
            face_ID2Path.addCurve(to: CGPoint(x: 52, y: 742.95), controlPoint1: CGPoint(x: 51.3, y: 736.05), controlPoint2: CGPoint(x: 52, y: 739.48))
            face_ID2Path.addLine(to: CGPoint(x: 52, y: 858))
            face_ID2Path.addLine(to: CGPoint(x: 52, y: 857.87))
            face_ID2Path.addCurve(to: CGPoint(x: 166.13, y: 972), controlPoint1: CGPoint(x: 52, y: 920.9), controlPoint2: CGPoint(x: 103.1, y: 972))
            face_ID2Path.addLine(to: CGPoint(x: 281, y: 972))
            face_ID2Path.addLine(to: CGPoint(x: 281, y: 972))
            face_ID2Path.addCurve(to: CGPoint(x: 307, y: 998), controlPoint1: CGPoint(x: 295.36, y: 972), controlPoint2: CGPoint(x: 307, y: 983.64))
            face_ID2Path.addCurve(to: CGPoint(x: 281, y: 1024), controlPoint1: CGPoint(x: 307, y: 1012.36), controlPoint2: CGPoint(x: 295.36, y: 1024))
            face_ID2Path.close()
            face_ID2Path.move(to: CGPoint(x: 512, y: 827))
            face_ID2Path.addLine(to: CGPoint(x: 511.68, y: 827))
            face_ID2Path.addCurve(to: CGPoint(x: 331.84, y: 756.16), controlPoint1: CGPoint(x: 444.93, y: 827), controlPoint2: CGPoint(x: 380.66, y: 801.68))
            face_ID2Path.addLine(to: CGPoint(x: 332.48, y: 756.75))
            face_ID2Path.addCurve(to: CGPoint(x: 331.14, y: 718.59), controlPoint1: CGPoint(x: 321.57, y: 746.58), controlPoint2: CGPoint(x: 320.97, y: 729.49))
            face_ID2Path.addCurve(to: CGPoint(x: 369.31, y: 717.25), controlPoint1: CGPoint(x: 341.31, y: 707.68), controlPoint2: CGPoint(x: 358.4, y: 707.08))
            face_ID2Path.addLine(to: CGPoint(x: 368.44, y: 716.45))
            face_ID2Path.addCurve(to: CGPoint(x: 652.85, y: 718.93), controlPoint1: CGPoint(x: 448.26, y: 790.89), controlPoint2: CGPoint(x: 571.74, y: 791.97))
            face_ID2Path.addLine(to: CGPoint(x: 654.69, y: 717.26))
            face_ID2Path.addCurve(to: CGPoint(x: 692.86, y: 718.59), controlPoint1: CGPoint(x: 665.6, y: 707.09), controlPoint2: CGPoint(x: 682.69, y: 707.68))
            face_ID2Path.addCurve(to: CGPoint(x: 691.52, y: 756.75), controlPoint1: CGPoint(x: 703.03, y: 729.49), controlPoint2: CGPoint(x: 702.43, y: 746.58))
            face_ID2Path.addLine(to: CGPoint(x: 692.16, y: 756.16))
            face_ID2Path.addCurve(to: CGPoint(x: 512.32, y: 827), controlPoint1: CGPoint(x: 643.34, y: 801.68), controlPoint2: CGPoint(x: 579.07, y: 827))
            face_ID2Path.addLine(to: CGPoint(x: 512, y: 827))
            face_ID2Path.close()
            face_ID2Path.move(to: CGPoint(x: 497, y: 647))
            face_ID2Path.addLine(to: CGPoint(x: 475, y: 647))
            face_ID2Path.addLine(to: CGPoint(x: 475, y: 647))
            face_ID2Path.addCurve(to: CGPoint(x: 448, y: 620), controlPoint1: CGPoint(x: 460.09, y: 647), controlPoint2: CGPoint(x: 448, y: 634.91))
            face_ID2Path.addCurve(to: CGPoint(x: 475, y: 593), controlPoint1: CGPoint(x: 448, y: 605.09), controlPoint2: CGPoint(x: 460.09, y: 593))
            face_ID2Path.addLine(to: CGPoint(x: 497, y: 593))
            face_ID2Path.addLine(to: CGPoint(x: 496.98, y: 593))
            face_ID2Path.addCurve(to: CGPoint(x: 512, y: 577.98), controlPoint1: CGPoint(x: 505.28, y: 593), controlPoint2: CGPoint(x: 512, y: 586.28))
            face_ID2Path.addLine(to: CGPoint(x: 512, y: 386))
            face_ID2Path.addLine(to: CGPoint(x: 512, y: 386))
            face_ID2Path.addCurve(to: CGPoint(x: 539, y: 359), controlPoint1: CGPoint(x: 512, y: 371.09), controlPoint2: CGPoint(x: 524.09, y: 359))
            face_ID2Path.addCurve(to: CGPoint(x: 566, y: 386), controlPoint1: CGPoint(x: 553.91, y: 359), controlPoint2: CGPoint(x: 566, y: 371.09))
            face_ID2Path.addLine(to: CGPoint(x: 566, y: 578))
            face_ID2Path.addLine(to: CGPoint(x: 566, y: 577.92))
            face_ID2Path.addCurve(to: CGPoint(x: 496.92, y: 647), controlPoint1: CGPoint(x: 566, y: 616.07), controlPoint2: CGPoint(x: 535.07, y: 647))
            face_ID2Path.addLine(to: CGPoint(x: 497, y: 647))
            face_ID2Path.close()
            face_ID2Path.move(to: CGPoint(x: 726.5, y: 487))
            face_ID2Path.addLine(to: CGPoint(x: 726.48, y: 487))
            face_ID2Path.addCurve(to: CGPoint(x: 701, y: 461.52), controlPoint1: CGPoint(x: 712.41, y: 487), controlPoint2: CGPoint(x: 701, y: 475.59))
            face_ID2Path.addLine(to: CGPoint(x: 701, y: 384.5))
            face_ID2Path.addLine(to: CGPoint(x: 701, y: 384.5))
            face_ID2Path.addCurve(to: CGPoint(x: 726.5, y: 359), controlPoint1: CGPoint(x: 701, y: 370.42), controlPoint2: CGPoint(x: 712.42, y: 359))
            face_ID2Path.addCurve(to: CGPoint(x: 752, y: 384.5), controlPoint1: CGPoint(x: 740.58, y: 359), controlPoint2: CGPoint(x: 752, y: 370.42))
            face_ID2Path.addLine(to: CGPoint(x: 752, y: 461.5))
            face_ID2Path.addLine(to: CGPoint(x: 752, y: 461.52))
            face_ID2Path.addCurve(to: CGPoint(x: 726.52, y: 487), controlPoint1: CGPoint(x: 752, y: 475.59), controlPoint2: CGPoint(x: 740.59, y: 487))
            face_ID2Path.addLine(to: CGPoint(x: 726.5, y: 487))
            face_ID2Path.close()
            face_ID2Path.move(to: CGPoint(x: 303.5, y: 487))
            face_ID2Path.addLine(to: CGPoint(x: 303.48, y: 487))
            face_ID2Path.addCurve(to: CGPoint(x: 278, y: 461.52), controlPoint1: CGPoint(x: 289.41, y: 487), controlPoint2: CGPoint(x: 278, y: 475.59))
            face_ID2Path.addLine(to: CGPoint(x: 278, y: 384.5))
            face_ID2Path.addLine(to: CGPoint(x: 278, y: 384.5))
            face_ID2Path.addCurve(to: CGPoint(x: 303.5, y: 359), controlPoint1: CGPoint(x: 278, y: 370.42), controlPoint2: CGPoint(x: 289.42, y: 359))
            face_ID2Path.addCurve(to: CGPoint(x: 329, y: 384.5), controlPoint1: CGPoint(x: 317.58, y: 359), controlPoint2: CGPoint(x: 329, y: 370.42))
            face_ID2Path.addLine(to: CGPoint(x: 329, y: 461.5))
            face_ID2Path.addLine(to: CGPoint(x: 329, y: 461.52))
            face_ID2Path.addCurve(to: CGPoint(x: 303.52, y: 487), controlPoint1: CGPoint(x: 329, y: 475.59), controlPoint2: CGPoint(x: 317.59, y: 487))
            face_ID2Path.addLine(to: CGPoint(x: 303.5, y: 487))
            face_ID2Path.close()
            face_ID2Path.move(to: CGPoint(x: 998, y: 307))
            face_ID2Path.addLine(to: CGPoint(x: 997.98, y: 307))
            face_ID2Path.addCurve(to: CGPoint(x: 972, y: 281.02), controlPoint1: CGPoint(x: 983.63, y: 307), controlPoint2: CGPoint(x: 972, y: 295.37))
            face_ID2Path.addLine(to: CGPoint(x: 972, y: 166))
            face_ID2Path.addLine(to: CGPoint(x: 972, y: 166.13))
            face_ID2Path.addCurve(to: CGPoint(x: 857.87, y: 52), controlPoint1: CGPoint(x: 972, y: 103.1), controlPoint2: CGPoint(x: 920.9, y: 52))
            face_ID2Path.addLine(to: CGPoint(x: 743, y: 52))
            face_ID2Path.addLine(to: CGPoint(x: 743.02, y: 52))
            face_ID2Path.addCurve(to: CGPoint(x: 717.01, y: 25.99), controlPoint1: CGPoint(x: 728.65, y: 52), controlPoint2: CGPoint(x: 717.01, y: 40.36))
            face_ID2Path.addCurve(to: CGPoint(x: 732.86, y: 2.05), controlPoint1: CGPoint(x: 717.01, y: 15.56), controlPoint2: CGPoint(x: 723.25, y: 6.13))
            face_ID2Path.addLine(to: CGPoint(x: 732.85, y: 2.05))
            face_ID2Path.addCurve(to: CGPoint(x: 742.95, y: -0), controlPoint1: CGPoint(x: 736.05, y: 0.7), controlPoint2: CGPoint(x: 739.48, y: -0))
            face_ID2Path.addLine(to: CGPoint(x: 858, y: -0))
            face_ID2Path.addCurve(to: CGPoint(x: 1024, y: 166), controlPoint1: CGPoint(x: 949.53, y: -0), controlPoint2: CGPoint(x: 1024, y: 74.47))
            face_ID2Path.addLine(to: CGPoint(x: 1024, y: 281))
            face_ID2Path.addLine(to: CGPoint(x: 1024, y: 281.02))
            face_ID2Path.addCurve(to: CGPoint(x: 998.02, y: 307), controlPoint1: CGPoint(x: 1024, y: 295.37), controlPoint2: CGPoint(x: 1012.37, y: 307))
            face_ID2Path.addLine(to: CGPoint(x: 998, y: 307))
            face_ID2Path.close()
            face_ID2Path.move(to: CGPoint(x: 26, y: 307))
            face_ID2Path.addLine(to: CGPoint(x: 25.98, y: 307))
            face_ID2Path.addCurve(to: CGPoint(x: -0, y: 281.02), controlPoint1: CGPoint(x: 11.63, y: 307), controlPoint2: CGPoint(x: -0, y: 295.37))
            face_ID2Path.addLine(to: CGPoint(x: 0, y: 166))
            face_ID2Path.addCurve(to: CGPoint(x: 166, y: -0), controlPoint1: CGPoint(x: 0, y: 74.47), controlPoint2: CGPoint(x: 74.47, y: -0))
            face_ID2Path.addLine(to: CGPoint(x: 281, y: -0))
            face_ID2Path.addLine(to: CGPoint(x: 280.98, y: -0))
            face_ID2Path.addCurve(to: CGPoint(x: 306.99, y: 26.01), controlPoint1: CGPoint(x: 295.35, y: -0), controlPoint2: CGPoint(x: 306.99, y: 11.64))
            face_ID2Path.addCurve(to: CGPoint(x: 291.14, y: 49.95), controlPoint1: CGPoint(x: 306.99, y: 36.44), controlPoint2: CGPoint(x: 300.75, y: 45.87))
            face_ID2Path.addLine(to: CGPoint(x: 291.15, y: 49.95))
            face_ID2Path.addCurve(to: CGPoint(x: 281.05, y: 52), controlPoint1: CGPoint(x: 287.95, y: 51.3), controlPoint2: CGPoint(x: 284.52, y: 52))
            face_ID2Path.addLine(to: CGPoint(x: 166, y: 52))
            face_ID2Path.addLine(to: CGPoint(x: 166.13, y: 52))
            face_ID2Path.addCurve(to: CGPoint(x: 52, y: 166.13), controlPoint1: CGPoint(x: 103.1, y: 52), controlPoint2: CGPoint(x: 52, y: 103.1))
            face_ID2Path.addLine(to: CGPoint(x: 52, y: 281))
            face_ID2Path.addLine(to: CGPoint(x: 52, y: 281.02))
            face_ID2Path.addCurve(to: CGPoint(x: 26.02, y: 307), controlPoint1: CGPoint(x: 52, y: 295.37), controlPoint2: CGPoint(x: 40.37, y: 307))
            face_ID2Path.addLine(to: CGPoint(x: 26, y: 307))
            face_ID2Path.close()
            fillColor.setFill()
            face_ID2Path.fill()

        }
    }
    
}
